Create initial JS structure, add NW script from tutorial part 1
loadero/examples pull request #1
Opened 2020-12-08 14:30 UTC by theRealAlpaca

- Update repo README
- Create intial JS examples structure
- Add NW script from "A beginners guide to test automation with Javascript(Nightwatch.js). Part 1."

2020-12-08 14:48 UTC, ajpetersons requested changes

2020-12-08 14:48 UTC, ajpetersons commented on README.md
> +![](assets/logo.svg)
maybe we have a public logo url?

2020-12-08 14:48 UTC, ajpetersons commented on javascript/README.md
> +Scripts are divided based on the resources where the script was used: [Wiki](https://wiki.loadero.com/) or [Blog](https://blog.loadero.com/). Then each folder is divided into subfolder that corespond
limit line length to 80. and personally i don't think that we need to split by blog/wiki, but rather theme of the content. for example, `custom commands`. that could be used in both wiki and blog

2020-12-08 14:48 UTC, ajpetersons commented on javascript/blog/nw_tutorial/part1/nightwatch_test_loadero.js
> +
extra whitespaces? GitHub shows "no newline at end of file"

2020-12-08 14:48 UTC, ajpetersons commented on javascript/blog/nw_tutorial/part1/nightwatch_test_loadero.js
> +        .pause(5 * 1000)
well, using `pause` to wait for event to happen is a very bad practice

2020-12-08 14:48 UTC, ajpetersons commented on javascript/blog/nw_tutorial/part1/nightwatch_test_loadero.js
> +        .takeScreenshot('nightwathcRepo.png');
```suggestion
        .takeScreenshot('nightwatchRepo.png');
```

2020-12-18 06:23 UTC, ajpetersons requested changes

2020-12-18 06:23 UTC, ajpetersons commented on .gitignore
> +# Logs
ever heard of gitignore.io ?

2020-12-18 06:23 UTC, ajpetersons commented on README.md
> +Change current active directory and follow execution instructions as per that
replace "Change current active directory" with "Head to the language-specific example directory"

2020-12-18 06:23 UTC, ajpetersons commented on README.md
> +folder's `README.md`.
instead of "folder" try to use "directory" consistently

2020-12-18 06:23 UTC, ajpetersons commented on javascript/README.md
> +tutorial blog series, check `nw_tutorial` folder. Each script also references
"Each script also references .." - that will be only true for blog articles. what about generic examples?

2020-12-18 06:23 UTC, ajpetersons commented on javascript/README.md
> +```
```suggestion
```bash
```

2020-12-18 06:23 UTC, ajpetersons commented on javascript/README.md
> +```
```suggestion
```bash
```

2020-12-18 06:23 UTC, ajpetersons commented on javascript/README.md
> +```
```suggestion
```bash
```

2020-12-18 06:23 UTC, ajpetersons commented on javascript/README.md
> +```
```suggestion
```bash
```

2020-12-18 06:23 UTC, ajpetersons commented on javascript/tests/nw_tutorial/part1/duckduckgo_test_local.js
> +};
```suggestion
};

```

2020-12-18 06:23 UTC, ajpetersons commented on javascript/tests/nw_tutorial/part1/duckduckgo_test_loadero.js
> +        .assert.containsText('#r1-0 .result__title', 'Nightwatch.js')
is it that fast? don't we need to wait until `#r1-0 .result__title`  appears?

2020-12-18 06:53 UTC, theRealAlpaca commented on .gitignore
> +# Logs
Yes but thought that will just clutter `.gitignore`. We can use Node template for now if we are fine with extra stuff

2020-12-18 06:53 UTC, theRealAlpaca commented on javascript/tests/nw_tutorial/part1/duckduckgo_test_loadero.js
> +        .assert.containsText('#r1-0 .result__title', 'Nightwatch.js')
Generally yes but here NW internal timeout of 5 seconds is used. It implies that if the element doesn't contain text within 5 seconds, the test fails. In addition, if this is changed, then it will be inconsistent with the blog post.

2020-12-18 07:04 UTC, ajpetersons commented on .gitignore
> +# Logs
that clutter has a reason

2020-12-18 07:59 UTC, merged