Loadero python showcase
loadero/examples pull request #15
Opened 2022-11-21 20:40 UTC by ruzv

2022-11-29 13:38 UTC, ajpetersons requested changes

2022-11-29 13:38 UTC, ajpetersons commented on .github/workflows/run-test.yml
> +  pull_request:
should we run on pull request or only on branches (master) ?

2022-11-29 13:38 UTC, ajpetersons commented on .github/workflows/update-tests.yml
> +          python update.py
are these commands joined together and we don't need `&&` between them?

2022-11-29 13:43 UTC, ajpetersons commented on python/src/loadero_python_showcase/configs/test_17705_script
>  };
what does the `17705` in the file name mean?

2022-12-01 06:47 UTC, ruzv commented on python/src/loadero_python_showcase/configs/test_17705_script
>  };
script file id

2022-12-01 06:47 UTC, ruzv commented on .github/workflows/run-test.yml
> +  pull_request:
that would make more sense, i just wanted something different from the other example

2022-12-01 07:15 UTC, ajpetersons commented on .github/workflows/run-test.yml
> +  pull_request:
This could trigger way too many runs and i'd rather avoid that. i think that in general a good practice is to not run such test pipelines on every PR.

2022-12-01 07:15 UTC, ajpetersons commented on python/src/loadero_python_showcase/configs/test_17705_script
>  };
could we update the file name to not hardcode file id?

2022-12-03 11:18 UTC, ruzv commented on python/src/loadero_python_showcase/configs/test_17705_script
>  };
sure

2022-12-05 10:18 UTC, merged