Parallel local test execution
loadero/examples pull request #19
Opened 2023-04-13 10:38 UTC by tjovcheska

2023-04-13 10:41 UTC, merinsTDL commented on python/src/parallel-local-test-execution/README.md
> +## Docker
Do we have a Dockerfile?

2023-04-13 10:43 UTC, merinsTDL commented on python/src/parallel-local-test-execution/requirements.txt
> +git+https://github.com/testdevlab/Py-TestUI@v1.1.0#egg=py_testui
Needs update to the public release of the latest tag. 
https://github.com/testdevlab/Py-TestUI/tags

2023-04-13 10:47 UTC, merinsTDL commented on python/src/parallel-local-test-execution/src/test_on_loadero.py
> +import pytest
Would be great to have the example code linted.

2023-04-13 10:50 UTC, merinsTDL commented on python/src/parallel-local-test-execution/src/test_on_loadero.py
> +# Test
Let's describe the scenario (in README) that Janus page is used and what are the steps executed by the participants.

2023-04-13 13:43 UTC, ajpetersons requested changes

2023-04-13 13:43 UTC, ajpetersons commented on python/src/parallel-local-test-execution/src/test_on_loadero.py
> +            print(f'Finished thread: {participant.participant_id} With code: {status}')
afaict `participant.participant_id` will remain to the value of last thread ID from the previous loop and this will log the same participant number all the time?

2023-04-13 13:55 UTC, ajpetersons commented on python/src/parallel-local-test-execution/src/test_on_loadero.py
> +            t = ThreadWithReturnValue(target=test, args=(d, participant.participant_id, ))
```suggestion
            t = ThreadWithReturnValue(target=test, args=(d, participant.participant_id))
```

2023-04-13 14:11 UTC, tjovcheska commented on python/src/parallel-local-test-execution/src/test_on_loadero.py
> +    pass
The pass keyword?

2023-04-13 15:01 UTC, tjovcheska commented on python/src/parallel-local-test-execution/src/test_on_loadero.py
> +            participant.participant_id += 1
Fixed.

2023-04-13 15:01 UTC, tjovcheska commented on python/src/parallel-local-test-execution/src/test_on_loadero.py
> +        participant.participant_id = GLOBALS[0]
Fixed.

2023-04-13 17:50 UTC, ajpetersons commented on python/src/parallel-local-test-execution/src/test_on_loadero.py
> +    pass
yes, afaict it is a noop and does nothing here

2023-04-14 06:26 UTC, ajpetersons commented on python/src/parallel-local-test-execution/src/test_on_loadero.py
> +@pytest.mark.loaderotest
```suggestion
@pytest.mark.demotest
```

2023-04-14 12:15 UTC, merged