Loadero manager and runner
loadero/examples pull request #21
Opened 2023-07-13 07:14 UTC by tjovcheska

2023-08-24 14:03 UTC, ajpetersons requested changes

2023-08-25 10:46 UTC, ajpetersons requested changes

2023-08-25 10:46 UTC, ajpetersons commented on python/src/loadero-manager-and-runner/loadero/runner.py
> +        APIClient(access_token=self.__access_token, project_id=self.__project_id)
do we need to re-initialize this? if we run 10 tests, we reinitialize 10 times. could initialize once in __init__

2023-08-25 10:46 UTC, ajpetersons commented on python/src/loadero-manager-and-runner/loadero/runner.py
> +    def wait_for_test_completion(self, test_id, run_id, logger):
i think this whole function can be replaced with `run.poll`: https://github.com/loadero/loadero-python#polling

2023-08-25 10:46 UTC, ajpetersons commented on python/src/loadero-manager-and-runner/loadero/runner.py
> +                        "was terminated due to timeout!")
can be if-elif-else

2023-08-25 10:46 UTC, ajpetersons commented on python/src/loadero-manager-and-runner/loadero/runner.py
> +                loadero_ids[p.pid] = [test_id, run_id]
as a general comment (not sure if worth changing) - we could store dict objects in `loadero_ids` list, then we wouldn't have to *know* that test id is element 0, we could just use `["test_id"]` notation

2023-08-28 08:17 UTC, tjovcheska commented on python/src/loadero-manager-and-runner/loadero_statistics.py
> +main()
This is Python 2 specific annotation. Our implementation works for v >= Python 3.

2023-08-28 08:43 UTC, tjovcheska commented on python/src/loadero-manager-and-runner/test_generator.py
> +main()
This is Python 2 specific annotation. Our implementation works for v >= Python 3.

2023-08-28 10:58 UTC, tjovcheska commented on python/src/loadero-manager-and-runner/loadero/runner.py
> +    def wait_for_test_completion(self, test_id, run_id, logger):
If we use the poll it will break the whole functionality with the timeouts that we have implemented.

2023-08-28 11:01 UTC, tjovcheska commented on python/src/loadero-manager-and-runner/loadero/runner.py
> +                loadero_ids[p.pid] = [test_id, run_id]
Here we have implemented a logic where the first element in the list will always be the test_id and the second one the run_id, so I think it's not worth it.

2023-08-28 11:04 UTC, tjovcheska commented on python/src/loadero-manager-and-runner/test_generator.py
> +default_test_id = randint(10000, 100000)
The whole module logic is based on this random generated test ids, because of the manager logic that is based on test ids. Any suggestion for creating a local test and restoring it to Loadero without random generated test ids?

2023-08-28 11:28 UTC, tjovcheska commented on python/src/loadero-manager-and-runner/test_generator.py
> +                group_dict = lm.create_group_from_cli(default_test["id"], default_name, default_num)
default_num is 1 by default. If the user choses to use the default_num then 1 group/participant/assert is created, else the specified number.

2023-08-28 11:30 UTC, tjovcheska commented on python/src/loadero-manager-and-runner/loadero/local_manager.py
> +            f"{str(test_dict['id'])}_{test_dict['name']}/participants.json")
It is creating the JSON object and adds the participants under group depending of the group id and at the end is writing in the file.

2023-08-28 15:16 UTC, ajpetersons commented on python/src/loadero-manager-and-runner/loadero/remote_manager.py
> +    def update_paricipant(self, participant):
typo in function name

2023-08-28 15:17 UTC, ajpetersons commented on python/src/loadero-manager-and-runner/loadero/action.py
> +    local_manager.read_project_from_file(local_project_id, local_project_name)
do we need this?

2023-08-28 15:18 UTC, ajpetersons commented on python/src/loadero-manager-and-runner/loadero/action.py
> +    if groups:
not needed

2023-08-28 15:18 UTC, ajpetersons commented on python/src/loadero-manager-and-runner/loadero/action.py
> +            if participants:
not needed

2023-08-28 15:18 UTC, ajpetersons commented on python/src/loadero-manager-and-runner/loadero/action.py
> +    if asserts:
not needed

2023-08-28 15:19 UTC, ajpetersons commented on python/src/loadero-manager-and-runner/loadero/action.py
> +                for participant in participants:
maybe we don't need to do this in every group? we could create a dict from local_group_id to new_group_id and we would have to loop this list only once

2023-08-28 15:21 UTC, ajpetersons commented on python/src/loadero-manager-and-runner/loadero/action.py
> +                for key in all_asserts_preconditions:
same as for participants - we could loop all preconditions only once and use a map from local_assert_id to new_assert_id

2023-08-28 15:21 UTC, ajpetersons commented on python/src/loadero-manager-and-runner/loadero/action.py
> +                            break
not sure what this does

2023-08-28 15:28 UTC, ajpetersons commented on python/src/loadero-manager-and-runner/loadero_statistics.py
> +main()
afaict it still works like that with python3. just that we are (currently) not importing these files, so we don't get random behaviour.
I checked with these files:
```py
# a.py
print("i am a")

def ffa():
    print("this is ffa()")
```

```py
# b.py
from a import ffa

print("i am b")
ffa()
```

`python3 b.py`

2023-08-28 15:53 UTC, ajpetersons requested changes

2023-08-28 15:53 UTC, ajpetersons commented on python/src/loadero-manager-and-runner/loadero/logger.py
> +        self.__logger.addHandler(sh)
could't we do all this during __init__? looks like most of the code is repeated all the time

2023-08-28 15:53 UTC, ajpetersons commented on python/src/loadero-manager-and-runner/loadero/remote_manager.py
> +    def read_test(self, test_id):
can't seem to find if this is ever used

2023-08-28 15:53 UTC, ajpetersons commented on python/src/loadero-manager-and-runner/loadero/remote_manager.py
> +    def read_group(self, test_id, group_id):
used?

2023-08-28 15:53 UTC, ajpetersons commented on python/src/loadero-manager-and-runner/loadero/remote_manager.py
> +    def read_group(self, test_id, group_id):
used?

2023-08-28 15:53 UTC, ajpetersons commented on python/src/loadero-manager-and-runner/loadero/remote_manager.py
> +    def delete_group(self, test_id, group_id):
used?

2023-08-28 15:53 UTC, ajpetersons commented on python/src/loadero-manager-and-runner/loadero/remote_manager.py
> +    def read_participant(self, test_id, participant_id):
used?

2023-08-30 11:50 UTC, tjovcheska commented on python/src/loadero-manager-and-runner/loadero/local_manager.py
> +        test["id"] = default_test["id"]
This id is not restoring to Loadero. After restoring the test gets new id from Loadero and the old one is used only for the first restore.

2023-08-30 11:52 UTC, tjovcheska commented on python/src/loadero-manager-and-runner/loadero/local_manager.py
> +                input_val = input(f"Enter group's {key}: [Default {n}] ")
It is 1. Defined in test-generator module.

2023-08-30 11:53 UTC, tjovcheska commented on python/src/loadero-manager-and-runner/loadero/local_manager.py
> +        participant_dict["group_id"] = group_id
We have random values before first restore. After that we use Loadero ones.

2023-08-30 11:54 UTC, tjovcheska commented on python/src/loadero-manager-and-runner/loadero/local_manager.py
> +        assert_dict["test_id"] = test_id
We have random values before first restore. After that we use Loadero ones.

2023-08-30 11:57 UTC, tjovcheska commented on python/src/loadero-manager-and-runner/loadero/local_manager.py
> +    def cli_input_asserts(list_of_choices, key):
Iterates different type of object.

2023-08-30 13:38 UTC, tjovcheska commented on python/src/loadero-manager-and-runner/test_manager.py
> +            act.backup(obj, args.suite, restored_test_ids, args.overwrite_suite, args.delete_source_test)
Migrate is doing backup of the test locally, and after that restore on the another project specified as destination.

2023-08-30 13:52 UTC, tjovcheska commented on python/src/loadero-manager-and-runner/loadero/action.py
> +                logger.critical("You must provide suite name to be overwritten! Action denied!")
Because not always the args_suite is provided. When it is provided with test_ids and overwrite_suite flag, there is separate action for each combination.

2023-08-30 14:04 UTC, tjovcheska commented on python/src/loadero-manager-and-runner/loadero/action.py
> +                            break
Cheks if assert precondition exists.

2023-08-30 16:24 UTC, tjovcheska commented on python/src/loadero-manager-and-runner/loadero/local_manager.py
> +            if not script or not os.path.exists(script):
We need to have the default script file because the test cannot be restored with missing script.

2023-08-30 16:28 UTC, tjovcheska commented on python/src/loadero-manager-and-runner/loadero/local_manager.py
> +        group["test_id"] = test_id
Same.

2023-08-30 16:31 UTC, tjovcheska commented on python/src/loadero-manager-and-runner/loadero/local_manager.py
> +    def get_project_name_from_test_cases(self, local_project_id):
Because this function checks if project exists locally.

2023-08-30 16:37 UTC, tjovcheska commented on python/src/loadero-manager-and-runner/loadero/local_manager.py
> +            local_project['updated'] = read_local_project['updated']
This logic was because of suites. If we have suites in the project file and read from remote the suites will be overwritten.

2023-08-30 16:39 UTC, tjovcheska commented on python/src/loadero-manager-and-runner/loadero/local_manager.py
> +            manager_config['suites'] = suites
Yes.

2023-08-30 16:41 UTC, tjovcheska commented on python/src/loadero-manager-and-runner/loadero/local_manager.py
> +            if content != read_content_json:
It the tests were previously backed up, maybe we want to know if something was changed on Loadero?

2023-08-30 16:51 UTC, tjovcheska commented on python/src/loadero-manager-and-runner/loadero/local_manager.py
> +            with open(absolute_path, "r", encoding="utf-8") as f:
We want to know if the test script on Loadero was updated before the current and latest backup.

2023-08-30 16:56 UTC, tjovcheska commented on python/src/loadero-manager-and-runner/loadero/local_manager.py
> +        for assert_id in asserts_ids:
Need to link the assert preconditions with the particular assert by id.

2023-08-30 16:58 UTC, tjovcheska commented on python/src/loadero-manager-and-runner/loadero/local_manager.py
> +            script_content = script_content.rstrip(script_content[-1])
The idea was to add \n if not exists on backup and remove on restore (because of VCS).

2023-08-31 08:43 UTC, ajpetersons commented on python/src/loadero-manager-and-runner/loadero_statistics.py
> +main()
will unresolve to double check the fix

2023-08-31 09:26 UTC, ajpetersons commented on python/src/loadero-manager-and-runner/loadero/action.py
> +                return new_suites
i think this is too nested inside the conditions now. we will return new_suites only in this specific case and in all other cases we will return nothing

2023-08-31 09:26 UTC, ajpetersons commented on python/src/loadero-manager-and-runner/loadero/action.py
> +                logger.critical("You must provide suite name to be overwritten! Action denied!")
still here we have 4 different conditions that essentially only check `if not args_suite`. i understand that there are different actions for different arg combinations, but most of the actions here require args_suite to be valid. therefore the function can be simplified a lot if we could check args_suite. realistically - `if not args_suite`, we will not do any actions and that can be checked quickly.

2023-08-31 12:36 UTC, ajpetersons requested changes

2023-08-31 20:04 UTC, tjovcheska commented on python/src/loadero-manager-and-runner/loadero/action.py
> +        else:
There will be always one file that will start with {local_manager.project_id}_. I don't get the point here.

2023-09-04 09:08 UTC, ajpetersons commented on python/src/loadero-manager-and-runner/loadero/action.py
> +        else:
imagine that we have 2 projects locally: `test_cases/1_first.project` and `test_cases/2_second.project`. what `init_handler` does is lists all files in `test_cases` directory and checks each one of them. imagine we are looking for `2_second` project. when this function executes `for directory in os.listdir("test_cases"):` for the first time, `directory=1_first.project`, meaning that this if condition will run the "else" branch.
similar problem will be if we have 2 projects and we look for the first one. first iteration will be success, but the next time dir name won't match the project we are looking for and we will end up in the else branch and overwrite `new_suites[args_suite]`

2023-09-04 10:23 UTC, ajpetersons commented on python/src/loadero-manager-and-runner/test_generator.py
> +default_test_id = randint(10000, 100000)
based on other conversations, do we keep the generator module for now?

2023-09-04 10:24 UTC, ajpetersons commented on python/src/loadero-manager-and-runner/test_generator.py
> +default_test_id = randint(10000, 100000)
if so, then that would resolve multiple of the open discussions

2023-09-04 18:29 UTC, tjovcheska commented on python/src/loadero-manager-and-runner/test_manager.py
> +            act.backup(obj, args.suite, restored_test_ids, args.overwrite_suite, args.delete_source_test)
Clone: INIT -> BACKUP -> RESTORE
Migrate: RESTORE -> INIT -> BACKUP

2023-09-04 18:33 UTC, tjovcheska commented on python/src/loadero-manager-and-runner/test_generator.py
> +default_test_id = randint(10000, 100000)
I think we can keep it. The randomly generated ids are not uploaded to Loadero. After restore we can do a backup and we will have the real ones. I will mention that in the text.

2023-09-04 18:37 UTC, tjovcheska commented on python/src/loadero-manager-and-runner/loadero/runner.py
> +    def wait_for_test_completion(self, test_id, run_id, logger):
We control the timeout from the main script test_runner. I think if we add the poll function here with its own timeout will break the logic.

2023-09-04 19:22 UTC, tjovcheska commented on python/src/loadero-manager-and-runner/loadero_statistics.py
> +            offset = max(0, min(offset, len(test_runs_results) - n))
I tried the both cases that you had mentioned before and it works.

2023-09-06 13:44 UTC, ajpetersons requested changes

2023-09-06 13:44 UTC, ajpetersons commented on python/src/loadero-manager-and-runner/loadero/runner.py
> +        # api_client: APIClient or None = None
why this line?

2023-09-06 13:44 UTC, ajpetersons commented on python/src/loadero-manager-and-runner/loadero/local_manager.py
> +            return
can be deleted - we will check the 2 just below

2023-09-06 13:44 UTC, ajpetersons commented on python/src/loadero-manager-and-runner/loadero/remote_manager.py
> +    __api_base = None
didn't we explicitly remove api base as a whole?

2023-09-06 13:44 UTC, ajpetersons commented on python/src/loadero-manager-and-runner/loadero/action.py
>      return new_suites
this seems to have changed logic. first of all, if project is not found by `find_project_name_by_project_id`, then we log critical where before we just returned default suites. and then if we do continue, we completely ignore precious suites though before we at least called `create_suites`

2023-09-06 13:56 UTC, ajpetersons commented on python/src/loadero-manager-and-runner/loadero/runner.py
> +    def wait_for_test_completion(self, test_id, run_id, logger):
we can supply arguments to the `run.poll(interval=10, timeout=timeout)` to specify custom timeouts as the user would provide via CLI

2023-09-06 14:01 UTC, ajpetersons commented on python/src/loadero-manager-and-runner/loadero_statistics.py
> +            offset = max(0, min(offset, len(test_runs_results) - n))
what i'm saying is - how can we get `offset != 0`?

2023-09-11 09:43 UTC, tjovcheska commented on python/src/loadero-manager-and-runner/loadero/action.py
>      return new_suites
Reverted logic

2023-11-01 16:33 UTC, ajpetersons requested changes

2023-11-01 16:33 UTC, ajpetersons commented on python/src/loadero-manager-and-runner/helpers/statistics_helpers.py
> +                "Proposed assert value\nagainst average standard deviation":
why does this title have `\n` in the middle?

2023-12-13 07:41 UTC, ajpetersons approved these changes

2023-12-19 10:31 UTC, merged