Add local and Loadero scripts from Nightwatch.js tutorial part 4
loadero/examples pull request #6
Opened 2021-11-23 15:34 UTC by theRealAlpaca

2021-11-24 13:23 UTC, ajpetersons requested changes

2021-11-24 13:23 UTC, ajpetersons commented on javascript/package.json
> +    "chromedriver": "95.0.0",
why not 96?

2021-11-24 13:23 UTC, ajpetersons commented on javascript/tests/nw_tutorial/part4/github_local.js
> +            client.url('https://github.com/').waitForElementVisible(prepare.container, 10 * 1000);
do we want url and credentials to be hardcoded in a mysterious place in script or as consts at the top of the file?

2021-11-24 13:56 UTC, ajpetersons requested changes

2021-11-24 13:56 UTC, ajpetersons commented on javascript/tests/nw_tutorial/part4/github_loadero.js
> +    // Element selectors boject
```suggestion
    // Element selectors object
```

2021-11-24 13:56 UTC, ajpetersons commented on javascript/tests/nw_tutorial/part4/github_local.js
> +        // Element selectors boject
```suggestion
        // Element selectors object
```

2021-11-24 15:16 UTC, theRealAlpaca commented on javascript/package.json
> +    "chromedriver": "95.0.0",
Didn't have GC 96 at that point. Will update 😉

2021-11-24 15:18 UTC, theRealAlpaca commented on javascript/tests/nw_tutorial/part4/github_local.js
> +            client.url('https://github.com/').waitForElementVisible(prepare.container, 10 * 1000);
It would make sense to be extracted as a `const` if URLs changed during the script (or if it would be reused).  For a short script like this it's fine IMO

2021-11-25 06:27 UTC, ajpetersons commented on javascript/tests/nw_tutorial/part4/github_local.js
> +            client.url('https://github.com/').waitForElementVisible(prepare.container, 10 * 1000);
for a short script splitting it in 7 functions is not necessary too

2021-11-25 08:03 UTC, theRealAlpaca commented on javascript/tests/nw_tutorial/part4/github_local.js
> +            client.url('https://github.com/').waitForElementVisible(prepare.container, 10 * 1000);
Then credentials (email & password) and timeout have to be extracted as well. I don't like extracting everything, especially for a simple script as this, and I'd like to keep as simple as possible and just explain the most important aspects of script refactoring. Additional variables such as timeout, URL, credentials and so on, ar test-specific but `selectors` and subfunctions are universal.

2021-11-25 08:47 UTC, ajpetersons commented on javascript/tests/nw_tutorial/part4/github_local.js
> +            client.url('https://github.com/').waitForElementVisible(prepare.container, 10 * 1000);
URL will almost never change during the script. for credential management i think we have separate articles. as for timeout - i think this still goes as a good practice tip to make it a constant. 

overall in the context of this blogpost i would want to see code with absolute good practice used. the argument that "script is simple" falls through, because then we should revert all changes made and only submit a spaghetti code.

2021-11-25 12:06 UTC, merged