Add python blog part 1 script examples
loadero/examples pull request #8
Opened 2022-01-18 15:59 UTC by ty-hob

2022-01-19 09:07 UTC, ajpetersons commented on python/src/part1/top_3_searches.py
> +        repeated_search(title)
this creates an interesting recursion. executing this function will change the search results page, so the each iteration of this "initial results" loop will have different page that it operates on

2022-01-19 13:32 UTC, theRealAlpaca reviewed
Once a link to Loadero blog article is know (ask sales representative for this). In the beginning of each file add a reference to the original article, similarly as it was done for NW examples (like [here](https://github.com/loadero/examples/blob/master/javascript/tests/nw_tutorial/part2/final_script_loadero.js))

2022-01-19 13:32 UTC, theRealAlpaca commented on python/src/part1/top_3_searches.py
> +        repeated_search(title)
I am honestly don't see a point in having a repeated search here. Maybe simplify this to just print out the top 3 search results and remove this function? 🤔

2022-01-19 13:32 UTC, theRealAlpaca commented on python/src/part1/top_3_searches.py
> +    # Opens the search engine duckduckgo.
```suggestion
    # Opens the search engine DuckDuckGo.
```

2022-01-19 13:32 UTC, theRealAlpaca commented on python/src/part1/top_3_searches.py
> +    # Locates search bar, wait for the element to load and sends search query
```suggestion
    # Locates search bar, waits for the element to load and sends a search query
```

2022-01-19 13:32 UTC, theRealAlpaca commented on python/src/part1/top_3_searches.py
> +    # Locates search button and clicks it. Notice that it is not necessary to
Why is not necessary to wait until the element is visible?

2022-01-19 13:32 UTC, theRealAlpaca commented on python/src/part1/top_3_searches.py
> +) -> list[str]:
Should it be `List[str]` based on his https://docs.python.org/3/library/typing.html#typing.List? Though in Loadero typing hints might throw errors since they are not imported.

2022-01-20 07:15 UTC, ty-hob commented on python/src/part1/top_3_searches.py
> +        ).wait_until_visible()
`clear` method dose not return self.

2022-01-20 07:15 UTC, ty-hob commented on python/src/part1/top_3_searches.py
> +        search_bar_element.send_keys(search_query)
nop

2022-01-20 07:24 UTC, ty-hob commented on python/src/part1/duckduckgo_click.py
> +    driver.e("css", "body").wait_until_visible()
aight, if ya say so. but this does what it says. with our without waiting for `body` to be visible, changes whether the screenshot is of google or duckduckgo.

2022-01-20 07:28 UTC, ty-hob commented on python/src/part1/top_3_searches.py
> +        # necessary to verify the presence of this element.
because previously the script has already validated that `search_bar` is visible. `search_bar` and `search_button` are in the same `div`. IMO not necessary to validate its visibility.

2022-01-20 12:01 UTC, ajpetersons approved these changes

2022-01-20 13:29 UTC, theRealAlpaca requested changes

2022-01-20 13:29 UTC, theRealAlpaca commented on python/src/part1/top_search_results.py
> +        # Locates the search element and verifies that it is present.
```suggestion
        # Locates the search element and verifies that it is visible.
```

2022-01-20 13:30 UTC, theRealAlpaca approved these changes

2022-01-20 13:35 UTC, theRealAlpaca approved these changes

2022-01-20 13:48 UTC, merged