py-local-setup: Add python local setup script examples
loadero/examples pull request #9
Opened 2022-05-19 09:42 UTC by ruzv

2022-05-19 12:35 UTC, ajpetersons requested changes

2022-05-19 12:35 UTC, ajpetersons commented on python/src/part2/loadero_script.py
> +# loadero_script.py
i think we might want 2 versions of this script - `loadero_script_local.py` and `loadero_script_loadero.py` - stripped version where only the `def test_on_loadero` is included for immediate upload to Loadero

2022-05-19 13:02 UTC, theRealAlpaca requested changes

2022-05-19 13:02 UTC, theRealAlpaca commented on python/src/part2/loadero_script.py
> +    print("test script execution finished")
```suggestion
    print("starting test script execution")

    yield driver

    print("test script execution finished")
```

2022-05-20 06:10 UTC, theRealAlpaca approved these changes

2022-05-20 06:55 UTC, ajpetersons commented on python/src/part2/loadero_script.py
> +# loadero_script.py
this is still an open question. if you look at https://github.com/loadero/examples/tree/master/javascript/tests/nw_tutorial/part1 , then there are versions to run locally as well as on Loadero

2022-05-20 07:08 UTC, ajpetersons approved these changes

2022-05-20 07:08 UTC, merged